# Generated by Django 3.2.5 on 2021-07-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(default='correoNoagregado@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='primerApellido',
            field=models.CharField(default='noAgregado', max_length=120),
        ),
        migrations.AddField(
            model_name='cliente',
            name='segundoApellido',
            field=models.CharField(default='noAgregado', max_length=120),
        ),
    ]
