# Generated by Django 3.2.5 on 2021-07-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20210730_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='primerApellido',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='segundoApellido',
            field=models.CharField(default='', max_length=120),
        ),
    ]
