# Generated by Django 3.2.5 on 2021-07-31 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfiles', '0001_initial'),
        ('clientes', '0003_auto_20210730_1924'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=120, null=True)),
                ('archivo_CSV', models.FileField(null=True, upload_to='csvs')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.FloatField(blank=True)),
                ('creado', models.DateTimeField(blank=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_orden', models.CharField(blank=True, max_length=12)),
                ('precio_total', models.FloatField(blank=True, null=True)),
                ('creado', models.DateTimeField(blank=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('ordenes', models.ManyToManyField(to='ventas.Orden')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.perfil')),
            ],
        ),
    ]
